// <auto-generated />
namespace PA.CampeonatoXadrez.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Criar_Banco : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Criar_Banco));
        
        string IMigrationMetadata.Id
        {
            get { return "201706211502411_Criar_Banco"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
